 version: 2
 jobs:
   build:
     machine:
       image: circleci/classic:edge
     steps:
       - checkout
       - run:
           name: docker-compose build
           command: docker-compose build
       - run:
           name: docker-compose up
           command: docker-compose up -d
       - run:
           name: sleep for waiting lanch db
           command: sleep 1
       - run:
           name: "before_test: setup db"
           command: docker-compose run web rake db:create db:migrate
       - run:
           name: test
           command: docker-compose run web rspec
       - run:
           name: docker-compose down
           command: docker-compose down
   test:
     docker:
       image: circleci/ruby:2.3.0-jessie-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: circleci-demo-ruby
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: circleci-demo-ruby
          POSTGRES_DB: rails_blog
          POSTGRES_PASSWORD: ""
     steps:
       - checkout
       - run:
          name: Which bundler?
          command: bundle -b
